// REVENUE   TARIFF Assumptions
export const revenuetariffAssumptions: any = {
  
    "id": "revenue___tariff",
    "name": "Revenue & Tariff",
    "icon": "💵",
    "color": "green",
    "headings": {
      "project_capacity": {
        "id": "project_capacity",
        "name": "Project Capacity",
        "assumptions": [
          {
            "id": "field_1176",
            "name": "First payment for ESF (only if not used as means of finacnce)",
            "row": 1176,
            "type": "input",
            "dataType": "currency",
            "value": 0,
            "formula": "= INDEX( $K1176:$Q1176, 0, LiveCase + 1 )",
            "isNamedCell": true,
            "required": false,
            "namedCell": "F1176",
            "unit": "USD",
            "section": "revenue___tariff",
            "heading": "project_capacity"
          }
        ]
      },
      "project_calculations": {
        "id": "project_calculations",
        "name": "Project Calculations",
        "assumptions": [
          {
            "id": "field_835",
            "name": "Overall Selected probability level",
            "row": 835,
            "type": "calculated",
            "dataType": "text",
            "value": "P50",
            "formula": "= IF( Refi_switch = 0, Selected_P_level, F834 )",
            "isNamedCell": false,
            "required": false,
            "section": "revenue___tariff",
            "heading": "project_calculations"
          }
        ]
      },
      "timeline_calculations": {
        "id": "timeline_calculations",
        "name": "Timeline Calculations",
        "assumptions": [
          {
            "id": "field_1185",
            "name": "REC Revenue period",
            "row": 1185,
            "type": "input",
            "dataType": "currency",
            "value": 0,
            "formula": "= INDEX( $K1185:$Q1185, 0, LiveCase + 1 )",
            "isNamedCell": true,
            "required": false,
            "namedCell": "F1185",
            "unit": "USD",
            "section": "revenue___tariff",
            "heading": "timeline_calculations"
          }
        ]
      },
      "operating_parameters": {
        "id": "operating_parameters",
        "name": "Operating Parameters",
        "assumptions": [
          {
            "id": "field_1132",
            "name": "Major maintenance required?",
            "row": 1132,
            "type": "input",
            "dataType": "number",
            "value": 0,
            "formula": "= INDEX( $K1132:$Q1132, 0, LiveCase + 1 )",
            "isNamedCell": true,
            "required": false,
            "namedCell": "F1132",
            "section": "revenue___tariff",
            "heading": "operating_parameters"
          },
          {
            "id": "field_1133",
            "name": "Time of maintenance",
            "row": 1133,
            "type": "input",
            "dataType": "number",
            "value": 0,
            "formula": "= INDEX( $K1133:$Q1133, 0, LiveCase + 1 )",
            "isNamedCell": true,
            "required": false,
            "namedCell": "F1133",
            "section": "revenue___tariff",
            "heading": "operating_parameters"
          },
          {
            "id": "field_1136",
            "name": "Major maintenance reserve considered?",
            "row": 1136,
            "type": "input",
            "dataType": "number",
            "value": 0,
            "formula": "= INDEX( $K1136:$Q1136, 0, LiveCase + 1 )",
            "isNamedCell": true,
            "required": false,
            "namedCell": "F1136",
            "section": "revenue___tariff",
            "heading": "operating_parameters"
          }
        ]
      },
      "revenue_structure": {
        "id": "revenue_structure",
        "name": "Revenue Structure",
        "assumptions": [
          {
            "id": "field_1185",
            "name": "REC Revenue period",
            "row": 1185,
            "type": "input",
            "dataType": "currency",
            "value": 0,
            "formula": "= INDEX( $K1185:$Q1185, 0, LiveCase + 1 )",
            "isNamedCell": true,
            "required": false,
            "namedCell": "F1185",
            "unit": "USD",
            "section": "revenue___tariff",
            "heading": "revenue_structure"
          }
        ]
      }
    },
    "fields": [
      {
        "id": "field_280",
        "name": "Bid bond LC charges",
        "row": 280,
        "type": "input",
        "dataType": "currency",
        "value": 0.005,
        "formula": "= INDEX( $K280:$Q280, 0, LiveCase + 1 )",
        "isNamedCell": true,
        "required": false,
        "unit": "USD",
        "namedCell": "F280",
        "section": "revenue___tariff"
      },
      {
        "id": "field_835",
        "name": "Overall Selected probability level",
        "row": 835,
        "type": "calculated",
        "dataType": "text",
        "value": "P50",
        "formula": "= IF( Refi_switch = 0, Selected_P_level, F834 )",
        "isNamedCell": false,
        "required": false,
        "section": "revenue___tariff"
      },
      {
        "id": "field_1013",
        "name": "January",
        "row": 1013,
        "type": "input",
        "dataType": "number",
        "value": 0.08187733874463768,
        "formula": "= INDEX( $K1013:$Q1013, 0, LiveCase + 1 )",
        "isNamedCell": true,
        "required": false,
        "namedCell": "F1013",
        "section": "revenue___tariff"
      },
      {
        "id": "field_1014",
        "name": "February",
        "row": 1014,
        "type": "input",
        "dataType": "number",
        "value": 0.08187733874463768,
        "formula": "= INDEX( $K1014:$Q1014, 0, LiveCase + 1 )",
        "isNamedCell": true,
        "required": false,
        "namedCell": "F1014",
        "section": "revenue___tariff"
      },
      {
        "id": "field_1015",
        "name": "March",
        "row": 1015,
        "type": "input",
        "dataType": "number",
        "value": 0.08187733874463768,
        "formula": "= INDEX( $K1015:$Q1015, 0, LiveCase + 1 )",
        "isNamedCell": true,
        "required": false,
        "namedCell": "F1015",
        "section": "revenue___tariff"
      },
      {
        "id": "field_1016",
        "name": "April",
        "row": 1016,
        "type": "input",
        "dataType": "number",
        "value": 0.08187733874463768,
        "formula": "= INDEX( $K1016:$Q1016, 0, LiveCase + 1 )",
        "isNamedCell": true,
        "required": false,
        "namedCell": "F1016",
        "section": "revenue___tariff"
      },
      {
        "id": "field_1017",
        "name": "May",
        "row": 1017,
        "type": "input",
        "dataType": "number",
        "value": 0.08703565308432823,
        "formula": "= INDEX( $K1017:$Q1017, 0, LiveCase + 1 )",
        "isNamedCell": true,
        "required": false,
        "namedCell": "F1017",
        "section": "revenue___tariff"
      },
      {
        "id": "field_1018",
        "name": "June",
        "row": 1018,
        "type": "input",
        "dataType": "number",
        "value": 0.08692018414746691,
        "formula": "= INDEX( $K1018:$Q1018, 0, LiveCase + 1 )",
        "isNamedCell": true,
        "required": false,
        "namedCell": "F1018",
        "section": "revenue___tariff"
      },
      {
        "id": "field_1019",
        "name": "July",
        "row": 1019,
        "type": "input",
        "dataType": "number",
        "value": 0.08288497698156663,
        "formula": "= INDEX( $K1019:$Q1019, 0, LiveCase + 1 )",
        "isNamedCell": true,
        "required": false,
        "namedCell": "F1019",
        "section": "revenue___tariff"
      },
      {
        "id": "field_1020",
        "name": "August",
        "row": 1020,
        "type": "input",
        "dataType": "number",
        "value": 0.08420167746888545,
        "formula": "= INDEX( $K1020:$Q1020, 0, LiveCase + 1 )",
        "isNamedCell": true,
        "required": false,
        "namedCell": "F1020",
        "section": "revenue___tariff"
      },
      {
        "id": "field_1021",
        "name": "September",
        "row": 1021,
        "type": "input",
        "dataType": "number",
        "value": 0.08571274697276351,
        "formula": "= INDEX( $K1021:$Q1021, 0, LiveCase + 1 )",
        "isNamedCell": true,
        "required": false,
        "namedCell": "F1021",
        "section": "revenue___tariff"
      },
      {
        "id": "field_1022",
        "name": "October",
        "row": 1022,
        "type": "input",
        "dataType": "number",
        "value": 0.08820452673693206,
        "formula": "= INDEX( $K1022:$Q1022, 0, LiveCase + 1 )",
        "isNamedCell": true,
        "required": false,
        "namedCell": "F1022",
        "section": "revenue___tariff"
      },
      {
        "id": "field_1023",
        "name": "November",
        "row": 1023,
        "type": "input",
        "dataType": "number",
        "value": 0.07756564885563856,
        "formula": "= INDEX( $K1023:$Q1023, 0, LiveCase + 1 )",
        "isNamedCell": true,
        "required": false,
        "namedCell": "F1023",
        "section": "revenue___tariff"
      },
      {
        "id": "field_1024",
        "name": "December",
        "row": 1024,
        "type": "input",
        "dataType": "number",
        "value": 0.07996523077386794,
        "formula": "= INDEX( $K1024:$Q1024, 0, LiveCase + 1 )",
        "isNamedCell": true,
        "required": false,
        "namedCell": "F1024",
        "section": "revenue___tariff"
      },
      {
        "id": "field_1027",
        "name": "January",
        "row": 1027,
        "type": "input",
        "dataType": "number",
        "value": 0.08254990986326788,
        "formula": "= INDEX( $K1027:$Q1027, 0, LiveCase + 1 )",
        "isNamedCell": true,
        "required": false,
        "namedCell": "F1027",
        "section": "revenue___tariff"
      },
      {
        "id": "field_1028",
        "name": "February",
        "row": 1028,
        "type": "input",
        "dataType": "number",
        "value": 0.07459429605362017,
        "formula": "= INDEX( $K1028:$Q1028, 0, LiveCase + 1 )",
        "isNamedCell": true,
        "required": false,
        "namedCell": "F1028",
        "section": "revenue___tariff"
      },
      {
        "id": "field_1029",
        "name": "March",
        "row": 1029,
        "type": "input",
        "dataType": "number",
        "value": 0.08455610041945606,
        "formula": "= INDEX( $K1029:$Q1029, 0, LiveCase + 1 )",
        "isNamedCell": true,
        "required": false,
        "namedCell": "F1029",
        "section": "revenue___tariff"
      },
      {
        "id": "field_1030",
        "name": "April",
        "row": 1030,
        "type": "input",
        "dataType": "number",
        "value": 0.08281785997179986,
        "formula": "= INDEX( $K1030:$Q1030, 0, LiveCase + 1 )",
        "isNamedCell": true,
        "required": false,
        "namedCell": "F1030",
        "section": "revenue___tariff"
      },
      {
        "id": "field_1031",
        "name": "May",
        "row": 1031,
        "type": "input",
        "dataType": "number",
        "value": 0.09056935297916638,
        "formula": "= INDEX( $K1031:$Q1031, 0, LiveCase + 1 )",
        "isNamedCell": true,
        "required": false,
        "namedCell": "F1031",
        "section": "revenue___tariff"
      },
      {
        "id": "field_1032",
        "name": "June",
        "row": 1032,
        "type": "input",
        "dataType": "number",
        "value": 0.08856914642043921,
        "formula": "= INDEX( $K1032:$Q1032, 0, LiveCase + 1 )",
        "isNamedCell": true,
        "required": false,
        "namedCell": "F1032",
        "section": "revenue___tariff"
      },
      {
        "id": "field_1033",
        "name": "July",
        "row": 1033,
        "type": "input",
        "dataType": "number",
        "value": 0.08315163405240297,
        "formula": "= INDEX( $K1033:$Q1033, 0, LiveCase + 1 )",
        "isNamedCell": true,
        "required": false,
        "namedCell": "F1033",
        "section": "revenue___tariff"
      },
      {
        "id": "field_1034",
        "name": "August",
        "row": 1034,
        "type": "input",
        "dataType": "number",
        "value": 0.08405078507830394,
        "formula": "= INDEX( $K1034:$Q1034, 0, LiveCase + 1 )",
        "isNamedCell": true,
        "required": false,
        "namedCell": "F1034",
        "section": "revenue___tariff"
      },
      {
        "id": "field_1035",
        "name": "September",
        "row": 1035,
        "type": "input",
        "dataType": "number",
        "value": 0.08515937601534031,
        "formula": "= INDEX( $K1035:$Q1035, 0, LiveCase + 1 )",
        "isNamedCell": true,
        "required": false,
        "namedCell": "F1035",
        "section": "revenue___tariff"
      },
      {
        "id": "field_1036",
        "name": "October",
        "row": 1036,
        "type": "input",
        "dataType": "number",
        "value": 0.08764184844351794,
        "formula": "= INDEX( $K1036:$Q1036, 0, LiveCase + 1 )",
        "isNamedCell": true,
        "required": false,
        "namedCell": "F1036",
        "section": "revenue___tariff"
      },
      {
        "id": "field_1037",
        "name": "November",
        "row": 1037,
        "type": "input",
        "dataType": "number",
        "value": 0.07701005799158428,
        "formula": "= INDEX( $K1037:$Q1037, 0, LiveCase + 1 )",
        "isNamedCell": true,
        "required": false,
        "namedCell": "F1037",
        "section": "revenue___tariff"
      },
      {
        "id": "field_1038",
        "name": "December",
        "row": 1038,
        "type": "input",
        "dataType": "number",
        "value": 0.07932963271110102,
        "formula": "= INDEX( $K1038:$Q1038, 0, LiveCase + 1 )",
        "isNamedCell": true,
        "required": false,
        "namedCell": "F1038",
        "section": "revenue___tariff"
      },
      {
        "id": "field_1117",
        "name": "January",
        "row": 1117,
        "type": "input",
        "dataType": "number",
        "value": 0,
        "formula": "= INDEX( $K1117:$Q1117, 0, LiveCase + 1 )",
        "isNamedCell": true,
        "required": false,
        "namedCell": "F1117",
        "section": "revenue___tariff"
      },
      {
        "id": "field_1118",
        "name": "February",
        "row": 1118,
        "type": "input",
        "dataType": "number",
        "value": 0,
        "formula": "= INDEX( $K1118:$Q1118, 0, LiveCase + 1 )",
        "isNamedCell": true,
        "required": false,
        "namedCell": "F1118",
        "section": "revenue___tariff"
      },
      {
        "id": "field_1119",
        "name": "March",
        "row": 1119,
        "type": "input",
        "dataType": "number",
        "value": 0,
        "formula": "= INDEX( $K1119:$Q1119, 0, LiveCase + 1 )",
        "isNamedCell": true,
        "required": false,
        "namedCell": "F1119",
        "section": "revenue___tariff"
      },
      {
        "id": "field_1120",
        "name": "April",
        "row": 1120,
        "type": "input",
        "dataType": "number",
        "value": 0,
        "formula": "= INDEX( $K1120:$Q1120, 0, LiveCase + 1 )",
        "isNamedCell": true,
        "required": false,
        "namedCell": "F1120",
        "section": "revenue___tariff"
      },
      {
        "id": "field_1121",
        "name": "May",
        "row": 1121,
        "type": "input",
        "dataType": "number",
        "value": 0,
        "formula": "= INDEX( $K1121:$Q1121, 0, LiveCase + 1 )",
        "isNamedCell": true,
        "required": false,
        "namedCell": "F1121",
        "section": "revenue___tariff"
      },
      {
        "id": "field_1122",
        "name": "June",
        "row": 1122,
        "type": "input",
        "dataType": "number",
        "value": 0,
        "formula": "= INDEX( $K1122:$Q1122, 0, LiveCase + 1 )",
        "isNamedCell": true,
        "required": false,
        "namedCell": "F1122",
        "section": "revenue___tariff"
      },
      {
        "id": "field_1123",
        "name": "July",
        "row": 1123,
        "type": "input",
        "dataType": "number",
        "value": 0,
        "formula": "= INDEX( $K1123:$Q1123, 0, LiveCase + 1 )",
        "isNamedCell": true,
        "required": false,
        "namedCell": "F1123",
        "section": "revenue___tariff"
      },
      {
        "id": "field_1124",
        "name": "August",
        "row": 1124,
        "type": "input",
        "dataType": "number",
        "value": 0,
        "formula": "= INDEX( $K1124:$Q1124, 0, LiveCase + 1 )",
        "isNamedCell": true,
        "required": false,
        "namedCell": "F1124",
        "section": "revenue___tariff"
      },
      {
        "id": "field_1125",
        "name": "September",
        "row": 1125,
        "type": "input",
        "dataType": "number",
        "value": 0,
        "formula": "= INDEX( $K1125:$Q1125, 0, LiveCase + 1 )",
        "isNamedCell": true,
        "required": false,
        "namedCell": "F1125",
        "section": "revenue___tariff"
      },
      {
        "id": "field_1126",
        "name": "October",
        "row": 1126,
        "type": "input",
        "dataType": "number",
        "value": 0,
        "formula": "= INDEX( $K1126:$Q1126, 0, LiveCase + 1 )",
        "isNamedCell": true,
        "required": false,
        "namedCell": "F1126",
        "section": "revenue___tariff"
      },
      {
        "id": "field_1127",
        "name": "November",
        "row": 1127,
        "type": "input",
        "dataType": "number",
        "value": 0,
        "formula": "= INDEX( $K1127:$Q1127, 0, LiveCase + 1 )",
        "isNamedCell": true,
        "required": false,
        "namedCell": "F1127",
        "section": "revenue___tariff"
      },
      {
        "id": "field_1128",
        "name": "December",
        "row": 1128,
        "type": "input",
        "dataType": "number",
        "value": 0,
        "formula": "= INDEX( $K1128:$Q1128, 0, LiveCase + 1 )",
        "isNamedCell": true,
        "required": false,
        "namedCell": "F1128",
        "section": "revenue___tariff"
      },
      {
        "id": "field_1132",
        "name": "Major maintenance required?",
        "row": 1132,
        "type": "input",
        "dataType": "number",
        "value": 0,
        "formula": "= INDEX( $K1132:$Q1132, 0, LiveCase + 1 )",
        "isNamedCell": true,
        "required": false,
        "namedCell": "F1132",
        "section": "revenue___tariff"
      },
      {
        "id": "field_1133",
        "name": "Time of maintenance",
        "row": 1133,
        "type": "input",
        "dataType": "number",
        "value": 0,
        "formula": "= INDEX( $K1133:$Q1133, 0, LiveCase + 1 )",
        "isNamedCell": true,
        "required": false,
        "namedCell": "F1133",
        "section": "revenue___tariff"
      },
      {
        "id": "field_1136",
        "name": "Major maintenance reserve considered?",
        "row": 1136,
        "type": "input",
        "dataType": "number",
        "value": 0,
        "formula": "= INDEX( $K1136:$Q1136, 0, LiveCase + 1 )",
        "isNamedCell": true,
        "required": false,
        "namedCell": "F1136",
        "section": "revenue___tariff"
      },
      {
        "id": "field_1171",
        "name": "Payment for ESF",
        "row": 1171,
        "type": "input",
        "dataType": "currency",
        "value": 0,
        "formula": "= INDEX( $K1171:$Q1171, 0, LiveCase + 1 )",
        "isNamedCell": true,
        "required": false,
        "namedCell": "F1171",
        "unit": "USD",
        "section": "revenue___tariff"
      },
      {
        "id": "field_1172",
        "name": "Payment for ESF",
        "row": 1172,
        "type": "calculated",
        "dataType": "currency",
        "value": 0,
        "formula": "= F1171 * EXR",
        "isNamedCell": false,
        "required": false,
        "unit": "USD",
        "section": "revenue___tariff"
      },
      {
        "id": "field_1175",
        "name": "First payment for ESF used as means of finance?",
        "row": 1175,
        "type": "input",
        "dataType": "currency",
        "value": 0,
        "formula": "= INDEX( $K1175:$Q1175, 0, LiveCase + 1 )",
        "isNamedCell": true,
        "required": false,
        "namedCell": "F1175",
        "unit": "USD",
        "section": "revenue___tariff"
      },
      {
        "id": "field_1176",
        "name": "First payment for ESF (only if not used as means of finacnce)",
        "row": 1176,
        "type": "input",
        "dataType": "currency",
        "value": 0,
        "formula": "= INDEX( $K1176:$Q1176, 0, LiveCase + 1 )",
        "isNamedCell": true,
        "required": false,
        "namedCell": "F1176",
        "unit": "USD",
        "section": "revenue___tariff"
      },
      {
        "id": "field_1177",
        "name": "Second payment for ESF?",
        "row": 1177,
        "type": "input",
        "dataType": "currency",
        "value": 0,
        "formula": "= INDEX( $K1177:$Q1177, 0, LiveCase + 1 )",
        "isNamedCell": true,
        "required": false,
        "namedCell": "F1177",
        "unit": "USD",
        "section": "revenue___tariff"
      },
      {
        "id": "field_1182",
        "name": "REC to be included in sponsor return",
        "row": 1182,
        "type": "input",
        "dataType": "number",
        "value": 0,
        "formula": "= INDEX( $K1182:$Q1182, 0, LiveCase + 1 )",
        "isNamedCell": true,
        "required": false,
        "namedCell": "F1182",
        "section": "revenue___tariff"
      },
      {
        "id": "field_1184",
        "name": "ProjCo share of REC",
        "row": 1184,
        "type": "input",
        "dataType": "number",
        "value": 0,
        "formula": "= INDEX( $K1184:$Q1184, 0, LiveCase + 1 )",
        "isNamedCell": true,
        "required": false,
        "namedCell": "F1184",
        "section": "revenue___tariff"
      },
      {
        "id": "field_1185",
        "name": "REC Revenue period",
        "row": 1185,
        "type": "input",
        "dataType": "currency",
        "value": 0,
        "formula": "= INDEX( $K1185:$Q1185, 0, LiveCase + 1 )",
        "isNamedCell": true,
        "required": false,
        "namedCell": "F1185",
        "unit": "USD",
        "section": "revenue___tariff"
      },
      {
        "id": "field_1191",
        "name": "Minimum gearing permissible",
        "row": 1191,
        "type": "input",
        "dataType": "number",
        "value": 0.65,
        "formula": "= INDEX( $K1191:$Q1191, 0, LiveCase + 1 )",
        "isNamedCell": true,
        "required": false,
        "namedCell": "F1191",
        "section": "revenue___tariff"
      },
      {
        "id": "field_1192",
        "name": "Maximum gearing permissible",
        "row": 1192,
        "type": "input",
        "dataType": "number",
        "value": 0.85,
        "formula": "= INDEX( $K1192:$Q1192, 0, LiveCase + 1 )",
        "isNamedCell": true,
        "required": false,
        "namedCell": "F1192",
        "section": "revenue___tariff"
      },
      {
        "id": "field_1194",
        "name": "Gearing input?",
        "row": 1194,
        "type": "input",
        "dataType": "number",
        "value": 1,
        "formula": "= INDEX( $K1194:$Q1194, 0, LiveCase + 1 )",
        "isNamedCell": true,
        "required": false,
        "namedCell": "F1194",
        "section": "revenue___tariff"
      },
      {
        "id": "field_1197",
        "name": "Drawdown method",
        "row": 1197,
        "type": "input",
        "dataType": "number",
        "value": 1,
        "formula": "= INDEX( $K1197:$Q1197, 0, LiveCase + 1 )",
        "isNamedCell": true,
        "required": false,
        "namedCell": "F1197",
        "section": "revenue___tariff"
      }
    ]
};

// Fields array is already included in the structure above
